Added Dependabot
OWASP/SKF-VideoEditorAPI pull request #5
Opened 2022-03-17 04:30 UTC by 0x41head

PR allows Dependabot to check for newer version of packets, once every weekday, for pip and github-actions

2022-03-17 06:02 UTC, ankit2001 commented
Hi @0x41head, thanks for the PR.
Lets change the check for dependencies to weekly, and add all other github actions in this PRs as well. 
I want to wrap all basic github actions in a single commit. 
Also whenver the PR is approved, try to squash them into a single commit.

2022-03-17 06:04 UTC, ankit2001 requested changes

2022-03-17 06:04 UTC, ankit2001 commented on .github/dependabot.yml
> +      interval: "daily"
Change it to weekly

2022-03-17 06:04 UTC, ankit2001 commented on .github/dependabot.yml
> +      interval: "daily"
Change it to weekly

2022-03-18 03:46 UTC, 0x41head commented
Hey @ankit2001, I tried creating the github actions yesterday, however, I ran into a roadblock.
There are barely any github actions in the marketplace for unassigning issues.
The closest thing I found was [this](https://github.com/JasonEtco/slash-assign-action)

What it does:

  - /assign assigns the issue to the one who commented.
  - Action won't work on an issue which has been assigned
  - After X days a warning is sent to the person regarding a stale issue
  - after Y days, the person is unassigned and the issue is open again
  - it open with an open label (or a label of your choice)
  
I can either use this or create one from scratch. However, I would rather not do the latter as that would involve creating an entirely new project.
Thanks

2022-03-19 11:29 UTC, ankit2001 commented
@0x41head  Use this one for now, it will be fine. 
Thanks.

2022-03-19 18:45 UTC, 0x41head commented
Hey @ankit2001, I think I have completed this PR.

What the github action does:

   - /assign assigns the issue to the one who commented.
   - Action won't work on an issue which has been assigned
   - After 7 days a warning is sent to the person regarding a stale issue
   - After another 7 days, the person is unassigned and the issue is open again
   - When a issue is assigned it automatically receives the assigned tag
   - If it is expected that the issue will take longer than 14 days, admin can add the WIP tag

@ankit2001 lmk if everything seems fine and I will squash all the commits
Thanks

2022-03-20 16:51 UTC, ankit2001 commented
Hi @0x41head, thanks for valuable contribution. 
We can go with this for now. Can change in future. 
Please squash the commits and write down a proper commit message.
Thanks.

2022-03-20 18:26 UTC, 0x41head commented
I squashed the commits. If it looks fine, I'll go with the same commit message for the UI repo as well.
Thanks

2022-03-20 19:20 UTC, ankit2001 commented
LGTM, Thanks @0x41head. 
You can go ahead with UI Repo as well.

2022-03-20 19:21 UTC, merged